<a href="https://colab.research.google.com/github/Maran27/Natural-Language-Processing/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = ["I am a good Boy", 
             "Australia Own the Ashes", 
             "India tour on South Africa", 
             "Omicron the Variant of concern", 
             "Un announces Code Red for Humanity", 
             "I am an Artificial Intelligence Developer"]

In [3]:
sentences

['I am a good Boy',
 'Australia Own the Ashes',
 'India tour on South Africa',
 'Omicron the Variant of concern',
 'Un announces Code Red for Humanity',
 'I am an Artificial Intelligence Developer']

In [4]:
vocabulary_size = 15000

One Hot Encoding

In [6]:
rep = [one_hot(words, vocabulary_size) for words in sentences] # will be getting the index from the dictionary
print(rep)

[[13799, 10365, 14971, 6977, 920], [14175, 12050, 7874, 9973], [2793, 5161, 3343, 6263, 8405], [11819, 7874, 6485, 1446, 12523], [10319, 9094, 6171, 3525, 7049, 2670], [13799, 10365, 3226, 9907, 2673, 4568]]


Embedding Layer Representation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
sen_len = 10
embedded = pad_sequences(rep, padding='post', maxlen = sen_len)
print(embedded)

[[13799 10365 14971  6977   920     0     0     0     0     0]
 [14175 12050  7874  9973     0     0     0     0     0     0]
 [ 2793  5161  3343  6263  8405     0     0     0     0     0]
 [11819  7874  6485  1446 12523     0     0     0     0     0]
 [10319  9094  6171  3525  7049  2670     0     0     0     0]
 [13799 10365  3226  9907  2673  4568     0     0     0     0]]


In [13]:
dim = 25

In [16]:
model = Sequential()
model.add(Embedding(vocabulary_size, 25, input_length=sen_len))
model.compile('adam', 'mse')

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 25)            375000    
                                                                 
Total params: 375,000
Trainable params: 375,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.predict(embedded)

array([[[-0.03734214, -0.02147948,  0.03583679, ...,  0.04093343,
         -0.04635065, -0.0128835 ],
        [ 0.03685961, -0.04111499, -0.00908816, ..., -0.01767679,
         -0.03131819, -0.00558751],
        [ 0.04466066, -0.04406607, -0.01579075, ...,  0.00766043,
          0.02109106,  0.0484695 ],
        ...,
        [ 0.01538685, -0.01340671, -0.01350565, ..., -0.02102709,
          0.03700404, -0.00647899],
        [ 0.01538685, -0.01340671, -0.01350565, ..., -0.02102709,
          0.03700404, -0.00647899],
        [ 0.01538685, -0.01340671, -0.01350565, ..., -0.02102709,
          0.03700404, -0.00647899]],

       [[ 0.03926824,  0.00297664, -0.01994711, ..., -0.0056386 ,
         -0.03211062,  0.02242302],
        [ 0.03128598,  0.02833368, -0.03399169, ..., -0.02511212,
         -0.03682674, -0.00437779],
        [-0.00470761, -0.02341245,  0.013009  , ..., -0.00905865,
          0.04032334,  0.02084236],
        ...,
        [ 0.01538685, -0.01340671, -0.01350565, ..., -

In [19]:
embedded[0]

array([13799, 10365, 14971,  6977,   920,     0,     0,     0,     0,
           0], dtype=int32)

In [20]:
print(model.predict(embedded)[0])

[[-3.73421423e-02 -2.14794762e-02  3.58367898e-02 -3.63919027e-02
   1.78255104e-02  4.83649634e-02  7.55252689e-03 -3.90160084e-03
  -3.37676033e-02  3.35322060e-02  4.81694937e-03  4.58577983e-02
  -3.59807499e-02 -3.81072648e-02  3.51992361e-02 -3.65171917e-02
   1.69236548e-02 -2.83477902e-02 -2.50856634e-02  1.20995753e-02
   4.55685370e-02  3.80150415e-02  4.09334339e-02 -4.63506468e-02
  -1.28834955e-02]
 [ 3.68596055e-02 -4.11149859e-02 -9.08815861e-03  1.78082697e-02
  -2.72776131e-02  2.37174369e-02  2.99238004e-02  2.08561756e-02
  -7.49161094e-03  2.50361823e-02 -2.02081557e-02 -4.83203642e-02
   1.37677044e-03 -3.81415486e-02  4.18027975e-02 -2.29405295e-02
   6.75562769e-03  3.59417461e-02  4.58333232e-02  2.20366605e-02
  -1.64324865e-02 -4.95990291e-02 -1.76767930e-02 -3.13181877e-02
  -5.58750704e-03]
 [ 4.46606614e-02 -4.40660715e-02 -1.57907493e-02 -2.27020271e-02
  -1.48339979e-02  5.73909283e-03  2.34178454e-03  1.43033601e-02
  -4.02890816e-02 -2.40971576e-02 -4.7